framework:
    secret: '%env(APP_SECRET)%'
    #default_locale: en
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: ~

    #esi: true
    #fragments: true
    php_errors:
        log: true

    property_info:
        enabled: true

    http_client:
        default_options:
            max_redirects: 7