# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - code-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
  web:
        image: nginx:latest
        ports:
            #- "8080:80"
            - "80:80"
        volumes:
            - ./:/var/www/employees
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
  php-fpm:
    build: docker/php-fpm
    volumes:
      - ./:/var/www/employees   
    networks:
      - code-network

networks:
    code-network:
        driver: bridge
